### ISSUE TITLE
Device discovered, but error code 8005 returned on slave device when trying to connect.

### ISSUE THREAD

**Issue by krokers** [googlesamples/android-nearby#12]
I have A problem with connecting specific devices using this application. Sample works fine for Nexus 7 + Nexus 5, and Nexus 7 + Samsung Galaxy S3, however, when I try to connect Nexus 5 to Samsung Galaxy S3 (and vice versa), I always get result 8005. Both devices are connected to the same WiFi, and it does support  mDNS discoverability. Any idea what might be the problem?

**Comment by easycheese** [comment]
Same here, Nexus 6p connecting to a Nexus 5.  Only happens occasionally though...I think it only occurs when the 6p is host.

**Comment by samtstern** [comment]
If you can reproduce this problem, please take a bug report and attach it here so that I can forward it on to the engineers responsible.

If you have never taken a bug report:
1.  Settings --> Developer Options
2.  Enable 'USB Debugging'
3.  Settings --> Developer Options --> Take bug report
4.  Wait 1-3 minutes and you will get a notification
5.  Share bug report to Google Drive / Dropbox / Etc
6.  Post link here
