### ISSUE TITLE
Wear to Wear communication?

### ISSUE THREAD

**Issue by narinearraul** [googlesamples/android-nearby#3]
Is there/will there be support for watch to watch communication using nearby api?

Thanks

**Comment by samtstern** [comment]
I'm not aware of any plan to support that use case.  Nearby Connections would not be a good fit for Wear, because it uses a constant WiFi connection which would drain the watch battery.  Nearby Connections uses Google Cloud Messaging, and I don't think that Android Wear devices can receive GCM without a phone.
