### ISSUE TITLE
Nearby API doesn't work without internet connection

### ISSUE THREAD

**Issue by isherenkov** [googlesamples/android-nearby#30]
I try to run the sample with internet connection turned off, and retrieve following error on Nearby.Messages.Subscribe

W/MainActivity: Could not subscribe, status = Status{statusCode=NETWORK_ERROR, resolution=null}

Checked on Nexus 5x android 6.0.1 and Nexus 6 android 5.1.1
Nearby permission granted, bluetooth is turned on.

I think there was a possibility to work without internet connection when I checked this sample few months ago. 
Is Nearby supposed to work offline now?

**Comment by samtstern** [comment]
@isherenkov this is working as intended.  You can see [in the documentation here](https://developers.google.com/nearby/messages/overview) that the Nearby Messages API can find nearby devices using bluetooth and other "offline" technologies, but the actual device-to-device communication requires an internet connection since it is mediated by the server.

**Comment by ravirajdarisi** [comment]
it will not work without internet connection, nearbyapi server provided authenticate tokens between the publishers and subscribers ,therefore message communication works..
